### ISSUE TITLE
Can you add the self-hosted doc URL to repo header?

### ISSUE THREAD

**Issue by meker12** [deconst/deconst-docs-control#15]
@smashwilson  -- Tiny fix that helps people get to hosted website. Can you add the URL for the deconst docs website to the repo header?  (Maybe I can't see because of permissions issue?).  I see the link in the Readme, but if it's at the top -- bonus no scrolling :-)

![website-url-for repo](https://cloud.githubusercontent.com/assets/6391769/12991726/2c45a500-d0d6-11e5-9e15-ffe1e89e5dc7.png)

Also,  I get security warning when I go to the URL.  You probably know that already.

**Comment by smashwilson** [comment]
Oh hey, good idea. I've added it to [deconst/deconst-docs](https://github.com/deconst/deconst-docs), as well.

> Also, I get security warning when I go to the URL. You probably know that already.

Yah, it's currently a self-signed certificate. deconst/deploy#95 will correct that... but there are some hurdles to overcome on the way there, I'm afraid.

**Comment by smashwilson** [comment]
Ah, forgot to close this one, too.
